# Setup
title:        Boldsparks
tagline:      Salesforce and other cloud technologies
baseurl:      ""
paginate:     1
permalink:    /:slug

# About/contact
author:
  name:       Sam Davyson
  url:        http://davyson.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
